spring:
  application:
    name: Lift Log Backend
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/liftlog
    username: liftlog
    password: liftlog
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

security:
  oauth2:
    client:
      clientId: 591997811673-8d8ipbtgbodbkovou20a57gcprk6beoo.apps.googleusercontent.com
      clientSecret: kO8UwJzZGiy6bXcKLxNKyTUJ
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.springframework.security: DEBUG
