# https://stackoverflow.com/questions/39690094/spring-boot-default-profile-for-integration-tests

spring:
  application:
    name: Lift Log Backend
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/liftlog
    username: liftlog
    password: liftlog
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

---

spring:
  profiles: test
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL   # TODO: Is there a point? No pg specific features are or should be used anyway
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

---

security:
  oauth2:
    client:
      clientId: 591997811673-8d8ipbtgbodbkovou20a57gcprk6beoo.apps.googleusercontent.com
      clientSecret: kO8UwJzZGiy6bXcKLxNKyTUJ
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.springframework.security: DEBUG
